import {analyzeOpportunity} from './analyzer';import {profiles} from './profiles';import type {InterviewQuestion,OpportunityInput} from './types';
const q=(category:InterviewQuestion['category'],priority:InterviewQuestion['priority'],question:string,why:string,answerGuide:string[],followUps:string[]):InterviewQuestion=>({category,priority,question,why,answerGuide,followUps});
export function generateInterviewQuestions(job:OpportunityInput):InterviewQuestion[]{const a=analyzeOpportunity(job),p=profiles[a.selectedProfile],text=job.description.toLowerCase(),out:InterviewQuestion[]=[];
if(text.includes('playwright'))out.push(q('TECHNICAL','MUST_PREPARE','How would you design a scalable Playwright + TypeScript framework for a large enterprise suite?','Playwright is explicitly required and is strongly evidenced in the selected resume.',['requirements and constraints','fixture strategy','page/component objects','test data and isolation','parallelism and CI','reporting/flakiness controls'],['How do you manage authentication?','How do you avoid flaky waits?','How do you shard tests?']));
if(text.includes('api'))out.push(q('ARCHITECTURE','MUST_PREPARE','How would you combine API and UI automation in one quality strategy?','The JD mentions API testing and the resume has API automation experience.',['test pyramid','API setup/teardown','contract validation','UI coverage boundaries','CI execution'],['What belongs at API vs UI level?','How do you handle test data?']));
if(text.includes('ai'))out.push(q('TECHNICAL','MUST_PREPARE','Where would you use AI in test planning, generation, failure analysis and healing, and how would you validate its output?','AI-assisted testing appears in the contract resume and this JD.',['use cases','RAG/context','guardrails','human review','evaluation metrics','failure modes'],['How do you prevent hallucinations?','RAG vs fine-tuning?','How do you measure quality?']));
out.push(q('RESUME','IMPORTANT','Walk me through an automation framework you personally designed and the trade-offs you made.','Framework architecture is a core resume strength.',['problem','constraints','architecture','implementation','measurable outcome'],['What would you redesign today?','How did you gain team adoption?']));
out.push(q('LEADERSHIP','IMPORTANT','How do you define an automation strategy across multiple teams without slowing delivery?','The selected profile emphasizes QA leadership and strategy.',['risk model','ownership','standards','CI gates','metrics','coaching'],['How do you handle resistance?','Which metrics matter?']));
for(const gap of a.missingSignals.slice(0,3))out.push(q('GAP','ADDITIONAL',`What is your practical experience with ${gap.toUpperCase()} and how would you use it in this role?`,`The JD/profile comparison does not show a strong ${gap} signal.`,['state actual experience only','connect adjacent experience','explain learning plan'],['What have you built with it?']));
out.push(q('SCENARIO','IMPORTANT','A previously stable CI suite suddenly becomes flaky after parallelization. How do you investigate it?','Senior automation roles commonly test debugging and systems thinking.',['reproduce','classify failures','isolate shared state','trace/network/logs','fix root cause','prevent recurrence'],['What metrics would you collect?']));
out.push(q('CODING','IMPORTANT','Implement a TypeScript helper that retries only transient API failures without hiding genuine defects.','The profile and likely roles require hands-on TypeScript/API automation.',['typed API','bounded retry','retryable status/errors','backoff','logging','tests'],['Why not retry assertions?']));return out}
