'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';

type Track='INDIA_FULL_TIME'|'GLOBAL_FULL_TIME'|'GLOBAL_B2B';
type Row={id:string;title:string;company:string;location?:string;compensation?:string|null;overallMatch:number;technicalMatch:number;responsibilityMatch:number;seniorityMatch:number;resumeEvidence:number;shortlistLikelihood?:string|null;indiaEligibility:string;employmentType:string;selectedProfile:string;matchedSkills?:string[]|null;missingSignals?:string[]|null;url:string;source?:string;discoveredAt:string;discoveryTrack?:Track|'OTHER';officialCareerUrl?:string;targetCompany?:string};
type Stats={total:number;new:number;applications:number;interviews:number;offers:number;rejected:number;actions:number};
type DiscoveryResponse={discovered?:number;added?:number;warnings?:string[];error?:string;companyScan?:{targeted:number;successful:number}};
const TRACKS:[Track,string,string][]=[['INDIA_FULL_TIME','India Full-Time','Senior roles in India'],['GLOBAL_FULL_TIME','Global Full-Time','Remote roles open to India'],['GLOBAL_B2B','Global Contract / B2B','International contracts']];
async function json<T>(r:Response):Promise<T>{const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(typeof b?.error==='string'?b.error:`Request failed (${r.status})`);return b as T}
function pretty(s:string){return s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
export default function Home(){
 const[rows,setRows]=useState<Row[]>([]),[stats,setStats]=useState<Stats|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[track,setTrack]=useState<Track>('INDIA_FULL_TIME'),[eligibility,setEligibility]=useState('ALL'),[min,setMin]=useState(55),[q,setQ]=useState('');
 const load=useCallback(async()=>{try{const[a,b]=await Promise.all([fetch('/api/opportunities?bucket=discovery',{cache:'no-store'}),fetch('/api/stats',{cache:'no-store'})]);const rs=await json<unknown>(a);setRows(Array.isArray(rs)?rs as Row[]:[]);setStats(await json<Stats>(b))}catch(e){setMessage(e instanceof Error?e.message:'Unable to load opportunities')}},[]);
 useEffect(()=>{void load()},[load]);
 const discover=async()=>{setBusy(true);setMessage('Scanning 100 official company career sites…');try{const d=await json<DiscoveryResponse>(await fetch('/api/discover',{method:'POST'}));const scan=d.companyScan;setMessage(`Scan complete: ${scan?.targeted??100} companies checked • ${scan?.successful??0} with extractable matching roles • ${d.discovered??0} roles found • ${d.added??0} new.${d.warnings?.length?' '+d.warnings.join(' '):''}`);await load()}catch(e){setMessage(e instanceof Error?e.message:'Discovery failed')}finally{setBusy(false)}};
 const status=async(id:string,s:string)=>{await json(await fetch('/api/applications/status',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id,status:s})}));await load()};
 const apply=async(id:string)=>{await json(await fetch('/api/applications',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({opportunityId:id})}));await load()};
 const counts=useMemo(()=>Object.fromEntries(TRACKS.map(([t])=>[t,rows.filter(r=>r.discoveryTrack===t).length])),[rows]);
 const shown=useMemo(()=>rows.filter(r=>r.discoveryTrack===track&&(eligibility==='ALL'||r.indiaEligibility===eligibility)&&r.overallMatch>=min&&(!q||`${r.title} ${r.company} ${r.location??''} ${(r.matchedSkills??[]).join(' ')}`.toLowerCase().includes(q.toLowerCase()))).sort((a,b)=>b.overallMatch-a.overallMatch),[rows,track,eligibility,min,q]);
 return <main className="shell">
  <section className="hero"><div><p className="eyebrow">PRIVATE JOB INTELLIGENCE</p><h1>Opportunity command center</h1><p className="hero-copy">Senior QA, Quality Engineering, SDET &amp; Test Architecture opportunities sourced primarily from official company career sites.</p></div><button className="button primary big" onClick={()=>void discover()} disabled={busy}>{busy?<><span className="spinner"/>Scanning companies…</>:'↻  Scan 100 companies'}</button></section>
  <nav className="main-nav"><a className="active" href="/">Discover</a><a href="/companies">100 Companies</a><a href="/applications">Applications</a><a href="/actions">Action Center{stats?.actions?` · ${stats.actions}`:''}</a><a href="/analytics">Analytics</a><a href="/settings">Settings</a></nav>
  {message&&<div className="notice">{message}</div>}
  <section className="metric-grid"><div className="metric"><span>New opportunities</span><strong>{stats?.new??0}</strong><small>Across monitored sources</small></div><div className="metric"><span>India senior</span><strong>{counts.INDIA_FULL_TIME??0}</strong><small>Full-time roles</small></div><div className="metric"><span>Global eligible</span><strong>{(counts.GLOBAL_FULL_TIME??0)+(counts.GLOBAL_B2B??0)}</strong><small>Full-time + B2B</small></div><div className="metric attention"><span>Needs attention</span><strong>{stats?.actions??0}</strong><small>Recruiter / interview actions</small></div></section>
  <section className="workspace"><aside className="filter-panel"><div><h3>Refine results</h3><button className="text-button" onClick={()=>{setEligibility('ALL');setMin(55);setQ('')}}>Reset</button></div><label>Search<input type="search" placeholder="Company, role, skill…" value={q} onChange={e=>setQ(e.target.value)}/></label><label>Eligibility<select value={eligibility} onChange={e=>setEligibility(e.target.value)}><option value="ALL">All eligible/unknown</option><option value="CONFIRMED">Confirmed</option><option value="LIKELY">Likely</option><option value="UNKNOWN">Needs review</option></select></label><label>Minimum match <b>{min}%</b><input type="range" min="0" max="95" value={min} onChange={e=>setMin(Number(e.target.value))}/></label><div className="source-note"><b>Source policy</b><p>Official company career pages are primary. Search APIs are fallback only.</p></div></aside>
   <div className="results"><div className="track-tabs">{TRACKS.map(([id,label,sub])=><button key={id} className={track===id?'selected':''} onClick={()=>setTrack(id)}><span>{label}<em>{counts[id]??0}</em></span><small>{sub}</small></button>)}</div><div className="result-head"><div><h2>{TRACKS.find(x=>x[0]===track)?.[1]}</h2><p>{shown.length} opportunities after filters</p></div><select aria-label="Sort"><option>Best match</option></select></div>
   {shown.length===0?<div className="empty-state"><div className="empty-icon">⌕</div><h3>No matching opportunities yet</h3><p>Run the company scan. If roles were found but are hidden, lower the match threshold or select another opportunity track.</p><button className="button primary" onClick={()=>void discover()} disabled={busy}>Scan official career sites</button></div>:shown.map(r=><article className="job-card" key={r.id}><div className="job-main"><div className="job-title-row"><div className="avatar">{r.company.slice(0,2).toUpperCase()}</div><div><p className="company-name">{r.company}</p><h3>{r.title}</h3><p className="job-meta">{r.location||'Location not stated'} <span>•</span> {r.source?.startsWith('official:')?'Official career site':r.source||'Career source'}</p></div><div className={`match-score ${r.overallMatch>=75?'strong':''}`}><strong>{r.overallMatch}%</strong><span>match</span></div></div><div className="badges"><span className="badge blue">{pretty(r.shortlistLikelihood??'UNKNOWN')} shortlist</span><span className="badge">{pretty(r.indiaEligibility)}</span><span className="badge">{pretty(r.employmentType)}</span><span className="badge">{pretty(r.selectedProfile)} CV</span>{r.seniorityMatch>=70&&<span className="badge green">Senior fit</span>}</div><div className="evidence"><p><b>Strong signals</b>{(r.matchedSkills??[]).slice(0,8).map(x=><span key={x}>{x}</span>)}</p>{(r.missingSignals??[]).length>0&&<p className="gaps"><b>Review gaps</b>{(r.missingSignals??[]).slice(0,5).map(x=><span key={x}>{x}</span>)}</p>}</div>{r.compensation&&<p className="comp">{r.compensation}</p>}</div><div className="job-actions"><a className="button primary" href={`/interview?id=${encodeURIComponent(r.id)}`}>Review match</a><a className="button ghost" href={r.url} target="_blank" rel="noreferrer">Official job ↗</a><div><button className="icon-btn" title="Shortlist" onClick={()=>void status(r.id,'SHORTLISTED')}>☆</button><button className="icon-btn" title="Mark applied" onClick={()=>void apply(r.id)}>✓</button><button className="icon-btn" title="Ignore" onClick={()=>void status(r.id,'IGNORED')}>×</button></div></div></article>)}</div>
  </section>
 </main>
}
