export type CompanyTier='PRODUCT'|'FINTECH'|'CONSULTING'|'INDIA_TECH';
export interface TargetCompany {name:string;careerUrl:string;tier:CompanyTier;priority:1|2;enabled:boolean;category?:string;majorHubs?:string[];aliases?:string[]}

/** Curated for senior QA/QE/SDET/automation relevance. Career URLs are official company-controlled entry points. */
const baseCompanies:TargetCompany[]=[
['Microsoft','https://jobs.careers.microsoft.com/global/en/search','PRODUCT',1],
['Google','https://www.google.com/about/careers/applications/jobs/results/','PRODUCT',1],
['Amazon','https://www.amazon.jobs/en/search','PRODUCT',1],
['Salesforce','https://careers.salesforce.com/en/jobs/','PRODUCT',1],
['Adobe','https://careers.adobe.com/us/en/search-results','PRODUCT',1],
['ServiceNow','https://careers.servicenow.com/jobs/','PRODUCT',1],
['Atlassian','https://www.atlassian.com/company/careers/all-jobs','PRODUCT',1],
['BrowserStack','https://www.browserstack.com/careers','PRODUCT',1],
['GitHub','https://www.github.careers/careers-home/jobs','PRODUCT',1],
['GitLab','https://about.gitlab.com/jobs/all-jobs/','PRODUCT',1],
['Canonical','https://canonical.com/careers/all','PRODUCT',1],
['Cloudflare','https://www.cloudflare.com/careers/jobs/','PRODUCT',1],
['Datadog','https://careers.datadoghq.com/all-jobs/','PRODUCT',1],
['Elastic','https://www.elastic.co/about/careers/open-positions','PRODUCT',1],
['MongoDB','https://www.mongodb.com/company/careers/teams/engineering','PRODUCT',1],
['IBM','https://www.ibm.com/careers/search','PRODUCT',1],
['Red Hat','https://www.redhat.com/en/jobs','PRODUCT',1],
['Oracle','https://careers.oracle.com/jobs/','PRODUCT',1],
['SAP','https://jobs.sap.com/','PRODUCT',1],
['Workday','https://workday.wd5.myworkdayjobs.com/Workday','PRODUCT',1],
['Intuit','https://jobs.intuit.com/search-jobs','PRODUCT',1],
['Cisco','https://jobs.cisco.com/jobs/SearchJobs/','PRODUCT',1],
['Dell Technologies','https://jobs.dell.com/en/search-jobs','PRODUCT',1],
['HPE','https://careers.hpe.com/us/en/search-results','PRODUCT',1],
['NVIDIA','https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite','PRODUCT',1],
['Broadcom','https://broadcom.wd1.myworkdayjobs.com/External_Career','PRODUCT',1],
['CrowdStrike','https://www.crowdstrike.com/en-us/careers/','PRODUCT',1],
['Palo Alto Networks','https://jobs.paloaltonetworks.com/en/jobs/','PRODUCT',1],
['Okta','https://www.okta.com/company/careers/','PRODUCT',1],
['Proofpoint','https://www.proofpoint.com/us/company/careers','PRODUCT',2],
['Zoom','https://careers.zoom.us/jobs/search','PRODUCT',2],
['HubSpot','https://www.hubspot.com/careers/jobs','PRODUCT',2],
['Twilio','https://www.twilio.com/en-us/company/jobs','PRODUCT',2],
['Dropbox','https://jobs.dropbox.com/all-jobs','PRODUCT',2],
['DocuSign','https://careers.docusign.com/jobs','PRODUCT',2],
['Snowflake','https://careers.snowflake.com/us/en/search-results','PRODUCT',1],
['Confluent','https://careers.confluent.io/jobs','PRODUCT',1],
['Databricks','https://www.databricks.com/company/careers/open-positions','PRODUCT',1],
['Stripe','https://stripe.com/jobs/search','FINTECH',1],
['PayPal','https://paypal.eightfold.ai/careers','FINTECH',1],
['Block','https://block.xyz/careers/jobs','FINTECH',1],
['Visa','https://corporate.visa.com/en/jobs/','FINTECH',1],
['Mastercard','https://careers.mastercard.com/us/en/search-results','FINTECH',1],
['American Express','https://aexp.eightfold.ai/careers','FINTECH',1],
['JPMorgan Chase','https://careers.jpmorgan.com/global/en/search-results','FINTECH',1],
['Goldman Sachs','https://higher.gs.com/results','FINTECH',1],
['Morgan Stanley','https://www.morganstanley.com/people-opportunities/students-graduates','FINTECH',2],
['Wells Fargo','https://www.wellsfargojobs.com/en/jobs/','FINTECH',2],
['Citi','https://jobs.citi.com/search-jobs','FINTECH',1],
['Barclays','https://search.jobs.barclays/','FINTECH',1],
['HSBC','https://www.hsbc.com/careers/find-a-job','FINTECH',1],
['Thomson Reuters','https://careers.thomsonreuters.com/us/en/search-results','FINTECH',1],
['Experian','https://jobs.smartrecruiters.com/Experian','FINTECH',1],
['Fidelity Investments','https://jobs.fidelity.com/en/jobs/','FINTECH',2],
['FIS','https://careers.fisglobal.com/us/en/search-results','FINTECH',2],
['Fiserv','https://www.careers.fiserv.com/search-jobs','FINTECH',2],
['Thoughtworks','https://www.thoughtworks.com/careers/jobs','CONSULTING',1],
['EPAM','https://www.epam.com/careers/job-listings','CONSULTING',1],
['Globant','https://career.globant.com/','CONSULTING',1],
['Endava','https://careers.endava.com/en/','CONSULTING',1],
['Nagarro','https://www.nagarro.com/en/careers','CONSULTING',1],
['Publicis Sapient','https://careers.publicissapient.com/jobs','CONSULTING',1],
['Accenture','https://www.accenture.com/in-en/careers/jobsearch','CONSULTING',1],
['Capgemini','https://www.capgemini.com/in-en/careers/join-capgemini/job-search/','CONSULTING',1],
['Cognizant','https://careers.cognizant.com/india-en/jobs/','CONSULTING',1],
['Wipro','https://careers.wipro.com/','INDIA_TECH',1],
['Infosys','https://digitalcareers.infosys.com/','INDIA_TECH',1],
['HCLTech','https://www.hcltech.com/careers','INDIA_TECH',1],
['LTIMindtree','https://careers.ltimindtree.com/','INDIA_TECH',1],
['Persistent Systems','https://careers.persistent.com/','INDIA_TECH',1],
['Coforge','https://careers.coforge.com/','INDIA_TECH',1],
['Mphasis','https://careers.mphasis.com/','INDIA_TECH',1],
['Genpact','https://www.genpact.com/careers/job-search','CONSULTING',1],
['CGI','https://cgi.njoyn.com/CGI/xweb/xweb.asp','CONSULTING',2],
['Deloitte','https://www2.deloitte.com/in/en/careers/search-jobs.html','CONSULTING',1],
['EY','https://careers.ey.com/','CONSULTING',1],
['KPMG','https://kpmg.com/in/en/home/careers.html','CONSULTING',2],
['PwC','https://www.pwc.in/careers.html','CONSULTING',2],
['TCS','https://www.tcs.com/careers','INDIA_TECH',1],
['Tech Mahindra','https://careers.techmahindra.com/','INDIA_TECH',1],
['Birlasoft','https://www.birlasoft.com/careers','INDIA_TECH',2],
['Hexaware','https://hexaware.com/careers/','INDIA_TECH',2],
['UST','https://www.ust.com/en/careers','CONSULTING',2],
['Virtusa','https://www.virtusa.com/careers','CONSULTING',2],
['Zensar','https://www.zensar.com/careers','INDIA_TECH',2],
['Paytm','https://paytm.com/careers/','INDIA_TECH',2],
['PhonePe','https://www.phonepe.com/careers/','FINTECH',1],
['Razorpay','https://razorpay.com/jobs/','FINTECH',1],
['Freshworks','https://www.freshworks.com/company/careers/','PRODUCT',1],
['Zoho','https://www.zoho.com/careers/','PRODUCT',2],
['Flipkart','https://www.flipkartcareers.com/#!/joblist','PRODUCT',1],
['Meesho','https://www.meesho.io/jobs','PRODUCT',1],
['Swiggy','https://careers.swiggy.com/','PRODUCT',2],
['Zomato','https://www.zomato.com/careers','PRODUCT',2],
['MakeMyTrip','https://careers.makemytrip.com/','PRODUCT',1],
['Walmart Global Tech','https://careers.walmart.com/technology','PRODUCT',1],
['Target','https://jobs.target.com/technology','PRODUCT',1],
['Uber','https://www.uber.com/us/en/careers/list/','PRODUCT',1],
['Airbnb','https://careers.airbnb.com/positions/','PRODUCT',2],
['Booking.com','https://careers.booking.com/','PRODUCT',2]
].map(([name,careerUrl,tier,priority])=>({name,careerUrl,tier,priority,enabled:true} as TargetCompany));




/** Additional real employers supplied by the user. Placeholder/fabricated TechCorp Unit-* rows are intentionally excluded. */
const expandedCompanies:TargetCompany[] = [
  {name:'Apple',careerUrl:'https://jobs.apple.com/en-in/search',tier:'PRODUCT',priority:1,enabled:true,category:'Global Product MNC',majorHubs:['Bengaluru','Hyderabad']},
  {name:'Meta',careerUrl:'https://www.metacareers.com/jobs/',tier:'PRODUCT',priority:1,enabled:true,category:'Global Product MNC',majorHubs:['Gurugram','Mumbai','Bengaluru']},
  {name:'Intel',careerUrl:'https://jobs.intel.com/en/search-jobs/India',tier:'PRODUCT',priority:1,enabled:true,category:'Semiconductor & Product',majorHubs:['Bengaluru','Hyderabad']},
  {name:'Qualcomm',careerUrl:'https://careers.qualcomm.com/careers',tier:'PRODUCT',priority:1,enabled:true,category:'Wireless & Product',majorHubs:['Hyderabad','Bengaluru','Chennai']},
  {name:'AMD',careerUrl:'https://careers.amd.com/careers-home/jobs',tier:'PRODUCT',priority:1,enabled:true,category:'Semiconductor & Product',majorHubs:['Bengaluru','Hyderabad']},
  {name:'Samsung R&D Institute India',careerUrl:'https://research.samsung.com/careers',tier:'PRODUCT',priority:1,enabled:true,category:'Product R&D',majorHubs:['Bengaluru','Noida']},
  {name:'Sony India Software Centre',careerUrl:'https://www.sonyjobs.com/',tier:'PRODUCT',priority:2,enabled:true,category:'Product & R&D',majorHubs:['Bengaluru']},
  {name:'Panasonic India',careerUrl:'https://www.panasonic.com/in/corporate/careers.html',tier:'PRODUCT',priority:2,enabled:true,category:'Product & R&D',majorHubs:['Bengaluru','Gurugram']},
  {name:'Siemens',careerUrl:'https://jobs.siemens.com/careers',tier:'PRODUCT',priority:1,enabled:true,category:'Industrial Technology',majorHubs:['Bengaluru','Pune','Chennai']},
  {name:'Bosch Global Software Technologies',careerUrl:'https://www.bosch-softwaretechnologies.com/en/careers/',tier:'PRODUCT',priority:1,enabled:true,category:'Automotive & IoT Technology',majorHubs:['Bengaluru','Coimbatore','Pune']},
  {name:'GE Vernova',careerUrl:'https://careers.gevernova.com/global/en/search-results',tier:'PRODUCT',priority:2,enabled:true,category:'Industrial Software',majorHubs:['Bengaluru','Hyderabad'],aliases:['GE Digital','General Electric Digital']},
  {name:'Schneider Electric',careerUrl:'https://www.se.com/ww/en/about-us/careers/job-search/',tier:'PRODUCT',priority:1,enabled:true,category:'Energy Management Technology',majorHubs:['Bengaluru']},
  {name:'Honeywell',careerUrl:'https://careers.honeywell.com/us/en/search-results',tier:'PRODUCT',priority:1,enabled:true,category:'Aerospace & Building Technology',majorHubs:['Bengaluru','Hyderabad','Madurai']},
  {name:'Philips',careerUrl:'https://www.careers.philips.com/professional/global/en/search-results',tier:'PRODUCT',priority:1,enabled:true,category:'HealthTech Product',majorHubs:['Bengaluru']},
  {name:"Lowe's India",careerUrl:'https://talent.lowes.com/in/en',tier:'PRODUCT',priority:1,enabled:true,category:'GCC / Retail Technology',majorHubs:['Bengaluru']},
  {name:'Tesco Bengaluru',careerUrl:'https://www.tesco-careers.com/technology/',tier:'PRODUCT',priority:2,enabled:true,category:'GCC / Retail Technology',majorHubs:['Bengaluru']},
  {name:'Autodesk',careerUrl:'https://autodesk.wd1.myworkdayjobs.com/Ext',tier:'PRODUCT',priority:1,enabled:true,category:'Design Software',majorHubs:['Bengaluru','Mumbai']},
  {name:'Synopsys',careerUrl:'https://careers.synopsys.com/',tier:'PRODUCT',priority:1,enabled:true,category:'EDA Software',majorHubs:['Bengaluru','Hyderabad','Noida']},
  {name:'Cadence Design Systems',careerUrl:'https://cadence.wd1.myworkdayjobs.com/External_Careers',tier:'PRODUCT',priority:1,enabled:true,category:'EDA Software',majorHubs:['Noida','Bengaluru','Hyderabad']},
  {name:'MathWorks',careerUrl:'https://in.mathworks.com/company/jobs/opportunities.html',tier:'PRODUCT',priority:1,enabled:true,category:'Mathematical Computing',majorHubs:['Bengaluru','Pune','Hyderabad']},
  {name:'NetApp',careerUrl:'https://careers.netapp.com/',tier:'PRODUCT',priority:1,enabled:true,category:'Data Management',majorHubs:['Bengaluru']},
  {name:'Akamai Technologies',careerUrl:'https://akamaicareers.inflightcloud.com/',tier:'PRODUCT',priority:1,enabled:true,category:'CDN & Cyber Security',majorHubs:['Bengaluru']},
  {name:'F5',careerUrl:'https://ffive.wd5.myworkdayjobs.com/f5jobs',tier:'PRODUCT',priority:1,enabled:true,category:'Application Delivery',majorHubs:['Hyderabad'],aliases:['F5 Networks']},
  {name:'Juniper Networks',careerUrl:'https://careers.juniper.net/',tier:'PRODUCT',priority:1,enabled:true,category:'Networking Technology',majorHubs:['Bengaluru']},
  {name:'Fortinet',careerUrl:'https://www.fortinet.com/corporate/careers',tier:'PRODUCT',priority:1,enabled:true,category:'Cyber Security',majorHubs:['Bengaluru','Pune']},
  {name:'Zscaler',careerUrl:'https://www.zscaler.com/careers/search',tier:'PRODUCT',priority:1,enabled:true,category:'Cyber Security',majorHubs:['Bengaluru','Chandigarh','Pune']},
  {name:'Informatica',careerUrl:'https://careers.informatica.com/',tier:'PRODUCT',priority:1,enabled:true,category:'Data Management Product',majorHubs:['Bengaluru']},
  {name:'Lenovo',careerUrl:'https://jobs.lenovo.com/en_US/careers',tier:'PRODUCT',priority:2,enabled:true,category:'Hardware & IT Product',majorHubs:['Bengaluru','Mumbai']},
  {name:'CitiusTech',careerUrl:'https://www.citiustech.com/careers',tier:'CONSULTING',priority:1,enabled:true,category:'Healthcare IT',majorHubs:['Mumbai','Bengaluru','Pune']},
  {name:'Standard Chartered',careerUrl:'https://scb.taleo.net/careersection/ex/jobsearch.ftl',tier:'FINTECH',priority:1,enabled:true,category:'GCC / FinTech',majorHubs:['Chennai','Bengaluru']},
  {name:'Deutsche Bank',careerUrl:'https://careers.db.com/search-jobs',tier:'FINTECH',priority:1,enabled:true,category:'GCC / FinTech',majorHubs:['Pune','Mumbai','Bengaluru']},
  {name:'Bank of America',careerUrl:'https://careers.bankofamerica.com/en-us/job-search',tier:'FINTECH',priority:1,enabled:true,category:'GCC / FinTech',majorHubs:['Hyderabad','Mumbai','Gurugram','Chennai']},
  {name:'HDFC Bank',careerUrl:'https://www.hdfcbank.com/personal/about-us/careers',tier:'FINTECH',priority:2,enabled:true,category:'Indian BFSI Technology',majorHubs:['Mumbai','Bengaluru']},
  {name:'EXL',careerUrl:'https://www.exlservice.com/careers',tier:'CONSULTING',priority:2,enabled:true,category:'BPO & IT Services',majorHubs:['Noida','Gurugram','Bengaluru','Pune']},
  {name:'WNS',careerUrl:'https://www.wns.com/careers',tier:'CONSULTING',priority:2,enabled:true,category:'BPO & IT Services',majorHubs:['Mumbai','Pune','Gurugram','Bengaluru']},
  {name:'NTT DATA',careerUrl:'https://careers.services.global.ntt/global/en',tier:'CONSULTING',priority:1,enabled:true,category:'Global IT Services',majorHubs:['Bengaluru','Pune','Hyderabad','Chennai']},
  {name:'Fujitsu',careerUrl:'https://www.fujitsu.com/global/about/careers/',tier:'CONSULTING',priority:2,enabled:true,category:'Global IT Services',majorHubs:['Pune','Bengaluru','Noida','Chennai']},
  {name:'DXC Technology',careerUrl:'https://careers.dxc.com/global/en/search-results',tier:'CONSULTING',priority:1,enabled:true,category:'Global IT Services',majorHubs:['Bengaluru','Hyderabad','Chennai','Noida']},
  {name:'Atos',careerUrl:'https://jobs.atos.net/',tier:'CONSULTING',priority:2,enabled:true,category:'Global IT Services',majorHubs:['Mumbai','Pune','Chennai'],aliases:['Atos Syntel']},
  {name:'Sonata Software',careerUrl:'https://www.sonata-software.com/careers',tier:'INDIA_TECH',priority:2,enabled:true,category:'IT Services',majorHubs:['Bengaluru','Mumbai','Hyderabad']},
  {name:'Happiest Minds',careerUrl:'https://www.happiestminds.com/careers/',tier:'INDIA_TECH',priority:2,enabled:true,category:'Digital Services',majorHubs:['Bengaluru','Pune','Noida']},
  {name:'Tata Elxsi',careerUrl:'https://www.tataelxsi.com/careers',tier:'INDIA_TECH',priority:1,enabled:true,category:'Design & Product Engineering',majorHubs:['Bengaluru','Thiruvananthapuram','Pune']},
  {name:'KPIT Technologies',careerUrl:'https://www.kpit.com/careers/',tier:'INDIA_TECH',priority:1,enabled:true,category:'Automotive Technology',majorHubs:['Pune','Bengaluru','Chennai','Kochi']},
  {name:'Cyient',careerUrl:'https://careers.cyient.com/',tier:'INDIA_TECH',priority:2,enabled:true,category:'Engineering & IT',majorHubs:['Hyderabad','Bengaluru']},
  {name:'GlobalLogic',careerUrl:'https://www.globallogic.com/career-search-page/',tier:'CONSULTING',priority:1,enabled:true,category:'Product Engineering',majorHubs:['Noida','Gurugram','Hyderabad','Bengaluru']},
  {name:'L&T Technology Services',careerUrl:'https://www.ltts.com/careers',tier:'INDIA_TECH',priority:1,enabled:true,category:'Engineering Services',majorHubs:['Vadodara','Bengaluru','Mysuru','Pune'],aliases:['LTTS']},
  {name:'3i Infotech',careerUrl:'https://www.3i-infotech.com/careers/',tier:'INDIA_TECH',priority:2,enabled:true,category:'IT Services',majorHubs:['Mumbai','Bengaluru','Hyderabad']},
  {name:'Sify Technologies',careerUrl:'https://www.sifytechnologies.com/careers/',tier:'INDIA_TECH',priority:2,enabled:true,category:'ICT & Cloud Services',majorHubs:['Chennai','Mumbai','Bengaluru']},
  {name:'Intellect Design Arena',careerUrl:'https://www.intellectdesign.com/careers/',tier:'PRODUCT',priority:2,enabled:true,category:'FinTech Products',majorHubs:['Chennai','Mumbai','Hyderabad']},
  {name:'Newgen Software',careerUrl:'https://newgensoft.com/company/careers/',tier:'PRODUCT',priority:2,enabled:true,category:'Low-Code Platform',majorHubs:['Noida','New Delhi']},
  {name:'Ramco Systems',careerUrl:'https://www.ramco.com/careers/',tier:'PRODUCT',priority:2,enabled:true,category:'Enterprise Software',majorHubs:['Chennai','Mumbai']},
  {name:'Quick Heal Technologies',careerUrl:'https://www.quickheal.co.in/careers',tier:'PRODUCT',priority:2,enabled:true,category:'Cyber Security Product',majorHubs:['Pune']},
  {name:'Subex',careerUrl:'https://www.subex.com/careers/',tier:'PRODUCT',priority:2,enabled:true,category:'Telecom Software',majorHubs:['Bengaluru']},
  {name:'Tejas Networks',careerUrl:'https://www.tejasnetworks.com/careers/',tier:'PRODUCT',priority:2,enabled:true,category:'Networking Products',majorHubs:['Bengaluru']}
];

const normalizeCompanyName=(name:string)=>name.toLowerCase().replace(/\b(india|systems|technologies|technology|inc|ltd|limited|corporation|corp|co)\b/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const merged=new Map<string,TargetCompany>();
for(const company of [...baseCompanies,...expandedCompanies]){
  const key=normalizeCompanyName(company.name);
  if(!merged.has(key)) merged.set(key,company);
}
export const targetCompanies:TargetCompany[]=[...merged.values()];
export const excludedPlaceholderPatterns=[/^TechCorp Systems Enterprise Ltd\. Unit-\d+$/i];
export function isRealTargetCompanyName(name:string){return !excludedPlaceholderPatterns.some(p=>p.test(name.trim()))}
